import { HttpException, HttpStatus } from '@nestjs/common';

export class BusinessException extends HttpException {
  public readonly code: string;

  constructor(code: string, message: string, status: HttpStatus = HttpStatus.BAD_REQUEST) {
    super({ success: false, code, message }, status);
    this.code = code;
  }
}

export const ErrorCode = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_PARAM: 'INVALID_PARAM',
  CHILD_NOT_FOUND: 'CHILD_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ALREADY_SUBMITTED: 'TASK_ALREADY_SUBMITTED',
  TASK_ALREADY_APPROVED: 'TASK_ALREADY_APPROVED',
  TASK_EXPIRED: 'TASK_EXPIRED',
  INVALID_TASK_STATUS: 'INVALID_TASK_STATUS',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  REWARD_NOT_FOUND: 'REWARD_NOT_FOUND',
  REWARD_INACTIVE: 'REWARD_INACTIVE',
  REWARD_OUT_OF_STOCK: 'REWARD_OUT_OF_STOCK',
  REWARD_HAS_REDEMPTIONS: 'REWARD_HAS_REDEMPTIONS',
  REDEMPTION_NOT_FOUND: 'REDEMPTION_NOT_FOUND',
  INVALID_REDEMPTION_STATUS: 'INVALID_REDEMPTION_STATUS',
  SMS_RATE_LIMIT: 'SMS_RATE_LIMIT',
  SMS_CODE_INVALID: 'SMS_CODE_INVALID',
  SMS_CODE_EXPIRED: 'SMS_CODE_EXPIRED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  SMS_NOT_CONFIGURED: 'SMS_NOT_CONFIGURED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',
  CHILD_LOGINNAME_CONFLICT: 'CHILD_LOGINNAME_CONFLICT',
} as const;
